# Generated by Django 4.1 on 2022-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0003_courses_paymentdetailes_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='SMS.student'),
        ),
    ]
